apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-vault-docker-login-buildkite-plugin
spec:
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: vault-docker-login-buildkite-plugin
    spec:
      provider_settings:
        build_branches: true
        build_pull_request_forks: false
        publish_commit_status: true
        publish_commit_status_per_step: false
      repository: elastic/vault-docker-login-buildkite-plugin
      teams:
        everyone:
          access_level: READ_ONLY
        platform-dev-flow: {}
  owner: group:platform-dev-flow
  type: buildkite-pipeline
