version: '3.7'
services:
  tests:
    image: buildkite/plugin-tester:v4.1.1@sha256:581f73aca88169912e23809f323437cced3cf22c28794bd7f96fbdf1c2caa5ab
    platform: linux/amd64
    volumes:
      - .:/plugin

  lint:
    image: buildkite/plugin-linter@sha256:edba1b12b590519384bd3916dfeb5ff8a3e78801968782411a0c356121744a0f
    command: ['--id', 'elastic/vault-docker-login']
    volumes:
      - ".:/plugin"

  shellcheck:
    image: koalaman/shellcheck:latest@sha256:bbc8c99df4eb97cab643054b7cfdf2ad802836a9fadd46b454c055a819697a41
    command: -x hooks/pre-command hooks/pre-exit
    working_dir: /plugin
    volumes:
      - ".:/plugin"
