version: '3.7'
services:
  tests:
    image: buildkite/plugin-tester:v4.3.0@sha256:86c728d8526e22f5d26c1b65e2cae1dfb2d9767fe24d560563895d051b258c84
    platform: linux/amd64
    volumes:
      - .:/plugin

  lint:
    image: buildkite/plugin-linter
    command: ['--id', 'elastic/vault-docker-login']
    volumes:
      - ".:/plugin"

  shellcheck:
    image: koalaman/shellcheck:latest
    command: -x hooks/pre-command hooks/pre-exit
    working_dir: /plugin
    volumes:
      - ".:/plugin"
