version: '3.7'
services:
  tests:
    image: buildkite/plugin-tester:v4.2.0@sha256:21067012f59af6b8316cceb95850e89a542b50338c72d209a68bbebb33aff8c3
    volumes:
      - .:/plugin

  lint:
    image: buildkite/plugin-linter
    command: ['--id', 'elastic/vault-docker-login']
    volumes:
      - ".:/plugin"

  shellcheck:
    image: koalaman/shellcheck:latest
    command: -x hooks/pre-command hooks/pre-exit
    working_dir: /plugin
    volumes:
      - ".:/plugin"
