version: '2.2'
services:
  tests:
    image: buildkite/plugin-tester:v4.1.1
    volumes:
      - .:/plugin

  lint:
    image: buildkite/plugin-linter
    command: ['--id', 'elastic/vault-docker-login']
    volumes:
      - ".:/plugin"

  shellcheck:
    image: koalaman/shellcheck:latest
    command: -x hooks/pre-command hooks/pre-exit
    working_dir: /plugin
    volumes:
      - ".:/plugin"