name: Vault Docker Login Buildkite Plugin
description: Logs into docker with credentials stored in vault
author: https://github.com/alpar-t
requirements: []
configuration:
  properties:
    secret_path:
      type: string
    disable_logout:
      type: boolean
    tool:
      type: string
  additionalProperties: false
