steps:
  - label: "Pre-commit"
    command: ".buildkite/scripts/pre-commit.sh"
    agents:
      image: "docker.elastic.co/ci-agent-images/ubuntu-build-essential"
  - label: ":sparkles: Buildkite plugin Lint"
    plugins:
      - plugin-linter#v3.0.0:
          id: elastic/vault-docker-login
