steps:
  - label: ":bash: Tests"
    command: "make tests"
    agents:
      provider: "gcp"
      image: family/core-ubuntu-2204

  - label: "foooo Tests"
    plugins:
      - plugin-tester#v1.1.1:
          folders:
            - tests
    agents:
      provider: "gcp"
      image: family/core-ubuntu-2204

  - label: ":shell: Shellcheck"
    command: "make shellcheck"
    agents:
      provider: "gcp"
      image: family/core-ubuntu-2204

  - label: "Pre-commit"
    command: "make pre-commit"
    agents:
      image: "docker.elastic.co/ci-agent-images/ubuntu-build-essential"

  - label: ":sparkles: Lint"
    command: "make lint"
    agents:
      provider: "gcp"
      image: family/core-ubuntu-2204
