#!/usr/bin/env bash

DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

# shellcheck source=lib/shared.bash
. "$DIR/../lib/shared.bash"

echo "~~~ Log out to $REGISTRY_HOSTNAME container registry"

if [[ "${BUILDKITE_PLUGIN_VAULT_DOCKER_LOGIN_DISABLE_LOGOUT:-false}" = "true" ]]; then
  echo 'WARNING: not logging out'
  exit 0
fi

if [[ -n "$BUILDKITE_PLUGIN_VAULT_DOCKER_LOGIN_TOOL" ]]; then
  logout "${BUILDKITE_PLUGIN_VAULT_DOCKER_LOGIN_TOOL}" "$REGISTRY_HOSTNAME"
  exit 0
fi

if is_tool_available "docker --version"; then
  docker_logout "$REGISTRY_HOSTNAME"

elif is_tool_available "buildah --version"; then
  buildah_logout "$REGISTRY_HOSTNAME"

elif is_tool_available "crane version"; then
  crane_logout "$REGISTRY_HOSTNAME"

elif is_tool_available "cosign version"; then
  cosign_logout "$REGISTRY_HOSTNAME"

elif is_tool_available "podman version"; then
  podman_logout "$REGISTRY_HOSTNAME"

elif is_tool_available "skopeo version"; then
  skopeo_logout "$REGISTRY_HOSTNAME"

else
  echo "No cli is available to auth. Delete creds from $HOME/.docker/config.json"
  rm "$HOME/.docker/config.json"
fi
