#!/bin/bash

if ! vault -v >/dev/null 2>&1; then
  echo "Could not find a vault cli to retrieve docker login secrets"
  exit 1
fi

DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

# shellcheck source=lib/shared.bash
. "$DIR/../lib/shared.bash"


if [[ "$BUILDKITE_PLUGIN_VAULT_DOCKER_LOGIN_SECRET_PATH" == kv* ]]; then
  VAULT_METHOD="kv get"
else
  VAULT_METHOD="read"
fi

# shellcheck disable=SC2086
REGISTRY_USERNAME=$(vault $VAULT_METHOD -field=username "$BUILDKITE_PLUGIN_VAULT_DOCKER_LOGIN_SECRET_PATH")
# shellcheck disable=SC2086
REGISTRY_PASSWORD=$(vault $VAULT_METHOD -field=password "$BUILDKITE_PLUGIN_VAULT_DOCKER_LOGIN_SECRET_PATH")
# shellcheck disable=SC2086
REGISTRY_HOSTNAME=$(vault $VAULT_METHOD -field=hostname "$BUILDKITE_PLUGIN_VAULT_DOCKER_LOGIN_SECRET_PATH")

echo "~~~ Log in to $REGISTRY_HOSTNAME container registry"

if is_tool_available "docker" "docker --version"; then
  echo "Logging in to $REGISTRY_HOSTNAME as $REGISTRY_USERNAME with docker cli"
  # For dockerhub we must unset the hostname argument during login
  # for credentials to be stored correctly in .docker/config.json
  # See: https://elasticco.atlassian.net/browse/REL-1195
  if [ "$REGISTRY_HOSTNAME" == "index.docker.io" ]; then
    REGISTRY_HOSTNAME=""
  fi
  docker login \
    --username "$REGISTRY_USERNAME" \
    --password "$REGISTRY_PASSWORD" \
    "$REGISTRY_HOSTNAME"

elif is_tool_available "buildah" "buildah --version"; then
  echo "Logging in to $REGISTRY_HOSTNAME as $REGISTRY_USERNAME with buildah cli"
  buildah login \
    --username "$REGISTRY_USERNAME" \
    --password "$REGISTRY_PASSWORD" \
    "$REGISTRY_HOSTNAME"

elif is_tool_available "crane" "crane version"; then
  echo "Logging in to $REGISTRY_HOSTNAME as $REGISTRY_USERNAME with crane cli"
  crane auth login \
    --username "$REGISTRY_USERNAME" \
    --password "$REGISTRY_PASSWORD" \
    "$REGISTRY_HOSTNAME"

elif is_tool_available "cosign" "cosign version"; then
  echo "Logging in to $REGISTRY_HOSTNAME as $REGISTRY_USERNAME with cosign cli"
  cosign login \
    --username "$REGISTRY_USERNAME" \
    --password "$REGISTRY_PASSWORD" \
    "$REGISTRY_HOSTNAME"

elif is_tool_available "podman" "podman version"; then
  echo "Logging in to $REGISTRY_HOSTNAME as $REGISTRY_USERNAME with podman cli"
  podman login \
    --username "$REGISTRY_USERNAME" \
    --password "$REGISTRY_PASSWORD" \
    "$REGISTRY_HOSTNAME"

elif is_tool_available "skopeo" "skopeo version"; then
  echo "Logging in to $REGISTRY_HOSTNAME as $REGISTRY_USERNAME with skopeo cli"
  skopeo login \
    --username "$REGISTRY_USERNAME" \
    --password "$REGISTRY_PASSWORD" \
    "$REGISTRY_HOSTNAME"

elif [[ -n "$BUILDKITE_PLUGIN_VAULT_DOCKER_LOGIN_TOOL" ]]; then
  echo "No cli tool called $BUILDKITE_PLUGIN_VAULT_DOCKER_LOGIN_TOOL is available to auth."
  exit 1

else
  echo "No cli is available to auth. Save creds to $HOME/.docker/config.json"
  mkdir -p "$HOME/.docker" && touch "$HOME/.docker/config.json"
  echo '{"auths": {"'"$REGISTRY_HOSTNAME"'": {"auth": "'"$(echo -n "$REGISTRY_USERNAME":"$REGISTRY_PASSWORD" | base64 --wrap=0)"'"}}}' >"$HOME/.docker/config.json"
fi

# export to help with the logout
export REGISTRY_HOSTNAME
