#!/bin/bash

if ! vault -v >/dev/null 2>&1; then
  echo "Could not find a vault cli to retrieve docker login secrets"
  exit 1
fi

DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

# shellcheck source=lib/shared.bash
. "$DIR/../lib/shared.bash"
# shellcheck source=lib/login.bash
. "$DIR/../lib/login.bash"

if [[ "$BUILDKITE_PLUGIN_VAULT_DOCKER_LOGIN_SECRET_PATH" == kv* ]]; then
  VAULT_METHOD="kv get"
else
  VAULT_METHOD="read"
fi

# shellcheck disable=SC2086
REGISTRY_USERNAME=$(vault $VAULT_METHOD -field=username "$BUILDKITE_PLUGIN_VAULT_DOCKER_LOGIN_SECRET_PATH")
# shellcheck disable=SC2086
REGISTRY_PASSWORD=$(vault $VAULT_METHOD -field=password "$BUILDKITE_PLUGIN_VAULT_DOCKER_LOGIN_SECRET_PATH")
# shellcheck disable=SC2086
REGISTRY_HOSTNAME=$(vault $VAULT_METHOD -field=hostname "$BUILDKITE_PLUGIN_VAULT_DOCKER_LOGIN_SECRET_PATH")

echo "~~~ Log in to $REGISTRY_HOSTNAME container registry"

if [[ -n "${BUILDKITE_PLUGIN_VAULT_DOCKER_LOGIN_TOOL}" ]]; then
  login "${BUILDKITE_PLUGIN_VAULT_DOCKER_LOGIN_TOOL}" "$REGISTRY_USERNAME" "$REGISTRY_PASSWORD" "$REGISTRY_HOSTNAME"
  exit 0
fi

if is_tool_available "docker --version"; then
  docker_login "$REGISTRY_USERNAME" "$REGISTRY_PASSWORD" "$REGISTRY_HOSTNAME"

elif is_tool_available "buildah --version"; then
  buildah_login "$REGISTRY_USERNAME" "$REGISTRY_PASSWORD" "$REGISTRY_HOSTNAME"

elif is_tool_available "crane version"; then
  crane_login "$REGISTRY_USERNAME" "$REGISTRY_PASSWORD" "$REGISTRY_HOSTNAME"

elif is_tool_available "cosign version"; then
  cosign_login "$REGISTRY_USERNAME" "$REGISTRY_PASSWORD" "$REGISTRY_HOSTNAME"

elif is_tool_available "podman version"; then
  podman_login "$REGISTRY_USERNAME" "$REGISTRY_PASSWORD" "$REGISTRY_HOSTNAME"

elif is_tool_available "skopeo version"; then
  skopeo_login "$REGISTRY_USERNAME" "$REGISTRY_PASSWORD" "$REGISTRY_HOSTNAME"

else
  echo "No cli is available to auth. Save creds to $HOME/.docker/config.json"
  mkdir -p "$HOME/.docker" && touch "$HOME/.docker/config.json"
  echo '{"auths": {"'"$REGISTRY_HOSTNAME"'": {"auth": "'"$(echo -n "$REGISTRY_USERNAME":"$REGISTRY_PASSWORD" | base64 --wrap=0)"'"}}}' >"$HOME/.docker/config.json"
fi

# export to help with the logout
export REGISTRY_HOSTNAME
